### ISSUE TITLE
missing run or map statement when requiring 'ammeter/init'

### ISSUE THREAD

**Issue by robinboening** [alexrothenberg/ammeter#59]
I am trying to use ammeter inside a rails engine (rails `5.0.4`) and rspec-rails (`3.6.0`).

I reduced my implementation as much as possible for this example:

```
# spec/generators/alchemy/elements_generator_spec.rb
require 'rails/all'
require 'rails/generators'
require 'rails/generators/alchemy/elements/elements_generator'
require 'ammeter/init'

module Alchemy
  RSpec.describe Generators::ElementsGenerator, type: :generator do
    destination File.expand_path("../../../tmp", __FILE__)

    before do
      before { prepare_destination }
      run_generator %w(elements)
    end

    describe "the view partial" do
      subject { file('views/alchemy/elements/all_you_can_eat_view.html.erb') }
      it { is_expected.to exist }
      ...
    end
  end
end
```

Stacktrace

```
$ bundle exec rspec spec/generators
An error occurred while loading ./spec/generators/alchemy/elements_generator_spec.rb.
Failure/Error: require 'ammeter/init'

RuntimeError:
  missing run or map statement
# ./spec/generators/alchemy/elements_generator_spec.rb:5:in `require'
# ./spec/generators/alchemy/elements_generator_spec.rb:5:in `<top (required)>'
```

Any ideas? What information could I provide more?

Thanks!

**Comment by robinboening** [comment]
I am sorry, I was able to solve my issue myself. I wasn't able to use the `spec_helper` because of a rails version mismatch in dummy's application.rb (expected rails v5.1). I can not really explain why the error with the run or map statement occured, but it was solved when I solved the version issue and when I was able to use the `spec_helper`.

Sorry and thanks a lot for this gem! 👍
